package com.maku.idleharvest.domain.models

import kotlinx.serialization.Serializable

/**
 * DePIN contribution tracking record.
 * Tracks resource sharing sessions with decentralized networks
 * and includes cryptographic proof of contribution.
 */
@Serializable
data class DePinContribution(
    val networkId: String,
    val networkName: String,
    val resourceType: ResourceType,
    val sessionId: String,
    val startedAt: Long,
    val endedAt: Long?,
    val earnedTokens: Double,
    val tokenSymbol: String,
    val proof: CryptographicProof?,
)

/**
 * Cryptographic proof of contribution for verifiable earning claims.
 * Contains session data and a signature generated by the device's secure keystore.
 *
 * Note: [proofData] and [signature] are Base64-encoded byte arrays for
 * cross-platform serialization compatibility.
 */
@Serializable
data class CryptographicProof(
    val sessionId: String,
    val proofData: String,
    val signature: String,
    val timestamp: Long,
)

/** An earning event from any monetization source. */
@Serializable
data class EarningEvent(
    val id: String,
    val source: EarningSource,
    val amountUsdc: Double,
    val amountLocal: Double?,
    val localCurrency: String?,
    val agentId: AgentId,
    val timestamp: Long,
)

/** Summary of total earnings across all sources and time periods. */
@Serializable
data class EarningsSummary(
    val totalEarnedUsdc: Double,
    val last24hUsdc: Double,
    val last7dUsdc: Double,
    val bySource: Map<EarningSource, Double>,
)
